name: Unzip and Commit

on:
  workflow_dispatch:   # se ejecuta a mano desde Actions
  push:
    branches: [ main ]
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 🔑 da permiso al workflow para hacer push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Descomprimir BarrileteCosmicTV.zip
        run: |
          if [ -f BarrileteCosmicTV.zip ]; then
            unzip -o BarrileteCosmicTV.zip -d .
            rm BarrileteCosmicTV.zip
          fi

      - name: Descomprimir scripts.zip
        run: |
          if [ -f scripts.zip ]; then
            unzip -o scripts.zip -d .
            rm scripts.zip
          fi

      - name: Commit y Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Archivos descomprimidos en la raíz" || echo "No hay cambios"
          git push
